# Generated by Django 4.2.7 on 2024-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Birthday', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('No_Years_of_Experiences', models.CharField(max_length=500)),
                ('No_Happy_Customers', models.CharField(max_length=500)),
                ('No_Project_Finished', models.CharField(max_length=500)),
                ('No_Digital_Awards', models.TextField(max_length=5000)),
            ],
        ),
    ]
