# Generated by Django 4.2.7 on 2024-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='No_Digital_Awards',
            field=models.CharField(max_length=5000),
        ),
    ]
