# Generated by Django 4.2.7 on 2024-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_description_alter_about_no_digital_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='v_c',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='v_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
