# Generated by Django 4.2.7 on 2024-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_about_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Email',
            field=models.CharField(max_length=500),
        ),
    ]
