# Generated by Django 4.2.7 on 2024-01-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_about_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Password',
        ),
    ]
