# Generated by Django 4.2.7 on 2024-01-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_about_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Password',
        ),
    ]
