# Generated by Django 4.2.7 on 2024-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_about_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
