# Generated by Django 4.2.7 on 2024-01-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_about_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Password',
            new_name='password',
        ),
    ]
