# Generated by Django 5.0.1 on 2024-02-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='division',
            new_name='Districts',
        ),
    ]
